services:
  axon-server:
    image: axoniq/axonserver:2025.2.0-SNAPSHOT
    ports:
      - "8024:8024"
      - "8124:8124"
    environment:
      axoniq_axonserver_hostname: axon-server
      axoniq_axonserver_autocluster_first: axon-server
      axoniq_axonserver_autocluster_contexts: _admin
    volumes:
      - data:/axonserver/data
      - events:/axonserver/events

volumes:
  db:
    driver: local
  data:
    driver: local
  events:
    driver: local